### ISSUE TITLE
Save files created by scripts are not put into tmp folder under Windows

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/Vereya#23]

**Comment by noskill** [comment]
I cant reproduce, @CICS-Oleg could you please check this issue?

**Comment by CICS-Oleg** [comment]
I don't get what is about? What save files? I've looked for a log file that has to be created in case of turned on logger. And it worked for me. Or is there some examles of using such save files?

**Comment by Necr0x0Der** [comment]
Closing since I cannot reproduce it anymore
